apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  cron: "0 3 * * *"
  task: "backup"
  retain: 5
  groups:
  - default
  labels:
    longhorn-backup: "true"
