apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  name: backup-daily
  cron: "0 3 * * *"
  task: "backup"
  retain: 5
  groups:
  - default
  concurrency: 1
  labels: 
    longhorn-backup: "true"
