apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-target-secret
  namespace: longhorn-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-backend
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-target-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: homelab/longhorn-system
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: homelab/longhorn-system
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: homelab/longhorn-system
        property: AWS_ENDPOINTS
    - secretKey: VIRTUAL_HOSTED_STYLE
      remoteRef:
        key: homelab/longhorn-system
        property: VIRTUAL_HOSTED_STYLE