apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - values.yaml
  - backup-job.yaml
  - external-secret.yaml
  - backup-target.yaml
  - ingress.yaml
  - snapshot-job.yaml
  # - longhorn-servicemonitor.yaml
