# Pool for General K8s Apps 
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: k8s-apps-pool
spec:
  blocks:
    - cidr: "192.168.1.128/26"
  allowFirstLastIPs: "Yes"
  serviceSelector:
    matchExpressions:
      - {key: io.cilium/network, operator: NotIn, values: [mgmt]}

---

# Pool for UniFi / Management (VLAN 20)
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: unifi-mgmt-pool
spec:
  blocks:
    - start: "192.168.30.10"
      stop: "192.168.30.10"
  serviceSelector:
    matchLabels:
      io.cilium/network: mgmt
