# Cilium Helm values translated from CLI flags

# Use eBPF to replace kube-proxy
kubeProxyReplacement: "true"

l2announcements:
  enabled: true

externalIPs:
  enabled: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

loadBalancer:
  algorithm: "maglev"

ipam:
  mode: "kubernetes"

# Enable the Cilium Ingress Controller
ingressController:
  enabled: true
  service:
    type: "LoadBalancer"
    loadBalancerMode: "shared"
