apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    serviceDiscovery:
      ingress: false
    providers:
      longhorn:
        url: https://cwk.longhorn
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - HomeLab:
        # - Proxmox VE:
        #     href: http://192.168.1.254:8006/
        #     description: Virtualization Management
        #     icon: proxmox.png
        - pgAdmin:
            href: http://cwk.pgadmin/
            description: Database GUI
            icon: pgadmin.svg
        - Network:
            - Unifi:
                href: https://192.168.1.130:8443/
                description: Unifi Controller
                icon: unifi.svg
            - Vodafone router:
                href: http://192.168.1.1/
                description: Vodafone Router
                icon: https://cdn.jsdelivr.net/npm/@mdi/svg/svg/router-wireless.svg
            - Pi-hole:
                href: http://192.168.1.5/admin/
                description: Ad-blocking DNS
                icon: pi-hole.svg
                widget:
                  type: pihole
                  version: 6
                  key: "{{HOMEPAGE_VAR_PIHOLE_WEBPASSWORD}}"

    - Cluster Management:
        - Longhorn:
            href: http://cwk.longhorn/
            description: Cluster Storage Management
            icon: longhorn.svg
        - Graylog:
            href: http://cwk.graylog/
            description: Log Management
            icon: graylog.svg
        - Grafana:
            href: http://cwk.grafana/
            description: Metrics Monitoring
            icon: grafana.svg
    - Misc:
        - Reading:
            - Wallabag:
                href: http://cwk.wallabag
                description: Read later application
                icon: wallabag.svg
        - Automation Tools:
            - n8n:
                href: http://cwk.n8n/
                description: Workflow Automation
                icon: n8n.svg
        - AI:
            - OpenWebUI:
                href: http://cwk.openwebui/
                description: Self-hosted Web UI for LLMs
                icon: open-webui.svg
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
        expanded: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
