apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - cluster_role.yaml
  - service_account.yaml
  - config_map.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
