apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress
  namespace: pihole
spec:
  ingressClassName: cilium
  rules:
    - host: "cwk.pihole"
      http:
        paths:
          - path: "/admin"
            pathType: Prefix
            backend:
              service:
                name: pihole
                port:
                  number: 80
