apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: "eu-west-2"
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: accessKeyID
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secretAccessKey
            namespace: external-secrets
