apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - external-secret.yaml
  - ingress.yaml
  - monitoring-rbac.yaml
configMapGenerator:
- name: grafana-values
  files:
  - values.yaml
generatorOptions:
  disableNameSuffixHash: true
